# Generated by Django 3.0.6 on 2020-05-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('news_type', models.CharField(choices=[('Bangla', 'bangla'), ('English', 'english')], default='Bangla', help_text='Type of the News', max_length=10)),
                ('author', models.CharField(help_text='Newspaper Name', max_length=100)),
                ('url', models.URLField(help_text='URL of the collected News')),
                ('headline', models.CharField(help_text='Headline of the News', max_length=200)),
                ('news_category', models.CharField(choices=[('Most Read', 'most_read'), ('Breaking News', 'breaking_news'), ('National', 'national'), ('Inter National', 'international'), ('Politics', 'politics'), ('Sports', 'sports'), ('Entertainment', 'entertainment'), ('Technology', 'technology')], default='Most Read', help_text='Category of the News', max_length=20)),
                ('published_time', models.DateTimeField(auto_now_add=True, help_text='Published Time')),
                ('summary', models.TextField(blank=True, help_text='Summary of the Collected News', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Collected News',
                'verbose_name_plural': 'Collected News',
            },
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['id', 'news_category', 'news_type', 'published_time'], name='news_proces_id_e6ed84_idx'),
        ),
    ]
